"""add kyoku to Round

Revision ID: 25061338f599
Revises: 2302a26ca41b
Create Date: 2024-08-14 01:37:40.216719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25061338f599'
down_revision = '2302a26ca41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kyoku', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_column('kyoku')

    # ### end Alembic commands ###
