"""add format to Image

Revision ID: 357c11add771
Revises: 2ec7f8847f38
Create Date: 2024-08-18 01:01:01.589327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357c11add771'
down_revision = '2ec7f8847f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('format', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('format')

    # ### end Alembic commands ###
