"""empty message

Revision ID: 6d640dea0d0a
Revises: 739b68568e54
Create Date: 2024-08-13 15:45:36.256069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d640dea0d0a'
down_revision = '739b68568e54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('melds', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_melds_round_detail_player_index', 'round_detail', ['player_index'], ['player_index'])

    with op.batch_alter_table('round_detail', schema=None) as batch_op:
        batch_op.drop_constraint('fk_round_detail_player_index', type_='foreignkey')
        batch_op.drop_column('balance')

    with op.batch_alter_table('wins', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_wins_round_detail_player_index', 'round_detail', ['player_index'], ['player_index'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('round_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_round_detail_player_index', 'players', ['player_index'], ['id'])

    with op.batch_alter_table('melds', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
