"""empty message

Revision ID: 739b68568e54
Revises: dcc74b4dc98c
Create Date: 2024-08-13 14:45:25.320840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739b68568e54'
down_revision = 'dcc74b4dc98c'
branch_labels = None
depends_on = None

# Check if table exists
def table_exists(table_name):
    inspector = sa.engine.reflection.Inspector.from_engine(op.get_bind())
    return table_name in inspector.get_table_names()

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('melds'):
        op.create_table('melds',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('round_id', sa.String(length=8), nullable=True),
        sa.Column('player_index', sa.String(length=2), nullable=True),
        sa.Column('turn', sa.Integer(), nullable=True),
        sa.Column('dora_pai', sa.Text(), nullable=True),
        sa.Column('type', sa.String(length=2), nullable=True),
        sa.Column('meld_pai', sa.String(length=2), nullable=True),
        sa.Column('meld_element', sa.Text(), nullable=True),
        sa.Column('meld_num', sa.Integer(), nullable=True),
        sa.Column('dahai', sa.String(length=2), nullable=True),
        sa.Column('tehai', sa.Text(), nullable=True),
        sa.Column('rinshan', sa.String(length=2), nullable=True),
        sa.Column('shanten_before', sa.Integer(), nullable=True),
        sa.Column('shanten_after', sa.Integer(), nullable=True),
        sa.Column('dora_num', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
        sa.ForeignKeyConstraint(['player_index'], ['round_detail.player_index'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if not table_exists('wins'):
            
        op.create_table('wins',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('round_id', sa.String(length=8), nullable=True),
        sa.Column('player_index', sa.String(length=2), nullable=True),
        sa.Column('type', sa.String(length=2), nullable=True),
        sa.Column('tenpai_type', sa.String(length=4), nullable=True),
        sa.Column('point', sa.Integer(), nullable=True),
        sa.Column('score_name', sa.String(length=5), nullable=True),
        sa.Column('han', sa.Integer(), nullable=True),
        sa.Column('fu', sa.Integer(), nullable=True),
        sa.Column('yaku', sa.Text(), nullable=True),
        sa.Column('dora', sa.Integer(), nullable=True),
        sa.Column('aka', sa.Integer(), nullable=True),
        sa.Column('ura', sa.Integer(), nullable=True),
        sa.Column('tehai', sa.Text(), nullable=True),
        sa.Column('win_pai', sa.String(length=2), nullable=True),
        sa.Column('deal_in', sa.String(length=6), nullable=True),
        sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
        sa.ForeignKeyConstraint(['player_index'], ['round_detail.player_index'], ),
        sa.PrimaryKeyConstraint('id')
        )
    with op.batch_alter_table('round_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_index', sa.String(length=2), nullable=False))
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(
            'fk_round_detail_player',  # 外部キー制約の名前
            'players',
            ['playerid'],
            ['id']
        )
        batch_op.create_foreign_key(
            'fk_round_detail_player_index',  # 外部キー制約の名前
            'players',
            ['player_index'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('round_detail', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('position',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('player_index')

    op.drop_table('wins')
    op.drop_table('melds')
    # ### end Alembic commands ###
