"""empty message

Revision ID: d0ba6cc13ced
Revises: 1234fb661b9e
Create Date: 2024-08-12 13:51:22.441888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ba6cc13ced'
down_revision = '1234fb661b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('seasonName', sa.String(length=20), nullable=True),
    sa.Column('regular', sa.Integer(), nullable=True),
    sa.Column('semi', sa.Integer(), nullable=True),
    sa.Column('final', sa.Integer(), nullable=True),
    sa.Column('regular_each', sa.Integer(), nullable=True),
    sa.Column('semi_each', sa.Integer(), nullable=True),
    sa.Column('final_each', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transfer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('old_playerid', sa.String(length=6), nullable=True),
    sa.Column('new_playerid', sa.String(length=6), nullable=True),
    sa.ForeignKeyConstraint(['new_playerid'], ['players.id'], ),
    sa.ForeignKeyConstraint(['old_playerid'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('penalty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resultid', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['resultid'], ['game_detail.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penalty')
    op.drop_table('transfer')
    op.drop_table('league')
    # ### end Alembic commands ###
