"""empty message

Revision ID: dcc74b4dc98c
Revises: d0ba6cc13ced
Create Date: 2024-08-13 13:35:25.646373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc74b4dc98c'
down_revision = 'd0ba6cc13ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rounds',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('gameid', sa.Integer(), nullable=True),
    sa.Column('round_name', sa.String(length=7), nullable=True),
    sa.Column('honba', sa.Integer(), nullable=True),
    sa.Column('kyotaku', sa.Integer(), nullable=True),
    sa.Column('dora', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['gameid'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('round_id', sa.String(length=8), nullable=True),
    sa.Column('log_id', sa.Integer(), nullable=True),
    sa.Column('cmd', sa.Text(), nullable=True),
    sa.Column('args', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('round_detail',
    sa.Column('round_id', sa.String(length=8), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('playerid', sa.String(length=6), nullable=True),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('richi', sa.Boolean(), nullable=True),
    sa.Column('meld_num', sa.Integer(), nullable=True),
    sa.Column('tenpai', sa.Boolean(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ),
    sa.PrimaryKeyConstraint('round_id', 'position')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('round_detail')
    op.drop_table('logs')
    op.drop_table('rounds')
    # ### end Alembic commands ###
